In [3]:
#filter
import numpy as np 
arr = np.array([10,20,30,40])
arr_f=arr[arr>20] #filter
print(arr_f)

[30 40]


In [5]:
arr = np.array([10,20,6,30,40])
arr_f=arr[arr!=6]
print(arr_f)

[10 20 30 40]


In [11]:
arr=np.array([1,2,3,4,5,12,15,16,20])
arr_f = arr[(arr >= 10) & (arr < 20)] 
print(arr_f)

[12 15 16]


In [12]:
#fnacy indexing
arr=np.array([10,20,30,40,2,3,100])
print(arr)
arr_f = arr[[[0,2]]]
print(arr_f)

[ 10  20  30  40   2   3 100]
[[10 30]]


In [13]:
#where 
arr=np.array([10,20,30,40,2,3,100])
print(arr)
arr_w=np.where(arr>9,"Trur","False")
print(arr_w)

[ 10  20  30  40   2   3 100]
['Trur' 'Trur' 'Trur' 'Trur' 'False' 'False' 'Trur']


In [ ]:

arr = np.array([10,20,3,4,14,15,16,90,100])
print(arr)
arr_w = np.where((arr>10) & (arr<20),arr*2,arr+2)
print(arr_w)



[ 10  20   3   4  14  15  16  90 100]
[ 12  22   5   6  28  30  32  92 102]


In [17]:
#adding nd removing data 
arr1=np.array([10,20,30])
arr2=np.array([1,2,3])

 
arr1_arr2 =np.concatenate((arr1, arr2), axis=0)
print(arr1_arr2)

arr1=np.array([[10,20,30],[40,50,60]])
arr2=np.array([[1,2,3],[4,5,6]])
arr1_arr2=np.concatenate((arr1,arr2))
print(arr1_arr2)

[10 20 30  1  2  3]
[[10 20 30]
 [40 50 60]
 [ 1  2  3]
 [ 4  5  6]]


In [18]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
result=np.vstack((arr1,arr2))
print(result)

[[1 2 3]
 [4 5 6]]


In [19]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
result=np.hstack((arr1,arr2))
print(result)

[1 2 3 4 5 6]


In [32]:
arr= np.array([2,3,4,5,6,7,8,45])
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.max(arr))
print(np.min(arr))


80
10.0
5.5
45
2


In [27]:
arr= np.array([2,3,4,5,6,7,8])
print(np.quantile(arr,0.3))

3.8


In [ ]:
#handling missing values
arr=np.array([10,20,np.nan,40])
print(arr)
#isnan is used to handle mising values
print(np.isnan(arr))
new_arr=np.nan_to_num(arr,nan=100)#null values ki jgh number print kra dega yh to awsome h yrr
print(new_arr)


[10. 20. nan 40.]
[False False  True False]
[ 10.  20. 100.  40.]


In [1]:
import numpy as np
sales_data = np.array([
[1,150000,180000,220000,250000], #Paradise Biryani
[2,120000,140000,160000,190000], #Bejing Bites
[3,200000,230000,260000,300000], #Pizza Hub
[4,180000,210000,240000,270000], #Burger Points
[5,160000,185000,205000,230000] #chain Point
])
print(sales_data)
print(sales_data.shape)
print(sales_data.ndim)
print(sales_data.size)
print(sales_data[:,0])
print(sales_data[:,1])
print(sales_data[:,4])
print(np.max(sales_data[:,1:]))
print(np.min(sales_data[:,1:]))
print(np.sum(sales_data[:,1]))
print(np.mean(sales_data[:,4]))
print(np.sum(sales_data[:,1:],axis=1)) #sum means adding
print(np.mean(sales_data[:,1:],axis=1)) #mean means avarage

[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]
(5, 5)
2
25
[1 2 3 4 5]
[150000 120000 200000 180000 160000]
[250000 190000 300000 270000 230000]
300000
120000
810000
248000.0
[800000 610000 990000 900000 780000]
[200000. 152500. 247500. 225000. 195000.]
