In [4]:
#numpy array operations 
import numpy as np
arr= np.array([1,2,3,4,5])
print(arr[3])

4


In [11]:
print(arr[0:4])#slicing 
print (arr[-1])
print(arr[:])
print(arr[0:4:2])#[start,stop,jump]
print(arr[::2])

[1 2 3 4]
5
[1 2 3 4 5]
[1 3]
[1 3 5]
