In [3]:
#filter
import numpy as np 
arr = np.array([10,20,30,40])
arr_f=arr[arr>20] #filter
print(arr_f)

[30 40]


In [5]:
arr = np.array([10,20,6,30,40])
arr_f=arr[arr!=6]
print(arr_f)

[10 20 30 40]


In [11]:
arr=np.array([1,2,3,4,5,12,15,16,20])
arr_f = arr[(arr >= 10) & (arr < 20)] 
print(arr_f)

[12 15 16]


In [12]:
#fnacy indexing
arr=np.array([10,20,30,40,2,3,100])
print(arr)
arr_f = arr[[[0,2]]]
print(arr_f)

[ 10  20  30  40   2   3 100]
[[10 30]]


In [13]:
#where 
arr=np.array([10,20,30,40,2,3,100])
print(arr)
arr_w=np.where(arr>9,"Trur","False")
print(arr_w)

[ 10  20  30  40   2   3 100]
['Trur' 'Trur' 'Trur' 'Trur' 'False' 'False' 'Trur']


In [14]:
#adding nd removing data 
arr = np.array([10,20,3,4,14,15,16,90,100])
print(arr)
arr_w = np.where((arr>10) & (arr<20),arr*2,arr+2)
print(arr_w)



[ 10  20   3   4  14  15  16  90 100]
[ 12  22   5   6  28  30  32  92 102]
