In [4]:
#numpy array operations 
import numpy as np
arr= np.array([1,2,3,4,5])
print(arr[3])

4


In [14]:
print(arr[0:4])#slicing 
print (arr[-1])
print(arr[:])
print(arr[0:4:2])#[start,stop,jump]
print(arr[::2])#jump by one
print(arr[::-1])#reverse can also be done by this 
print(arr[-2::])

[1 2 3 4]
5
[1 2 3 4 5]
[1 3]
[1 3 5]
[5 4 3 2 1]
[4 5]


In [ ]:
#2d arrays
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[0][0])
print(arr[0][2])
print(arr[:,1]) #all row | cols 0
print(arr[0,0])
print(arr[:,2])



[[1 2 3]
 [4 5 6]]
1
3
[2 5]
1
[3 6]


In [61]:
arr=np.array([[10,20],[30,40]])
print(arr)
print(arr[0,0])
print(arr[1,1])
print(arr[:,1])
print(arr[[0,1],[1,0]])
print(arr[[0,1],[0,1]])

[[10 20]
 [30 40]]
10
40
[20 40]
[20 30]
[10 40]


In [113]:
#3d [block,row,column]
arr = np.array([[[2,3],[4,5]],[[8,9],[6,7]]])
print(type(arr))
arr.ndim
print(arr)

<class 'numpy.ndarray'>
[[[2 3]
  [4 5]]

 [[8 9]
  [6 7]]]


In [67]:
#looping
arr = np.array([10,20,30,40,50])
print(arr)
for i in arr:
    print(i)

[10 20 30 40 50]
10
20
30
40
50


In [107]:
arr=np.array([[2453,75,183975],[5795,99,573705],[4100,36,147600],[7526,86,647236],[9528,45,428760],[107788,17,183396]])
#print(arr)
print(arr[4:,1])
print(arr[4:,2])
print(arr[2,0],arr[3:4,])
print(arr[0, :2],arr[[0,1],[2,1]])
print(arr[[2,3,3,3],[0,0,1,2]])

[45 17]
[428760 183396]
4100 [[  7526     86 647236]]
[2453   75] [183975     99]
[  4100   7526     86 647236]
