NUMPY START HO GYE H YWR

In [1]:
# numpy | list
import numpy as np
import time
 
# for list
start = time.time()
sum1 = 0
for i in range(1000000):
  sum1 += i*2
end = time.time()
print("for list",sum1,end-start)
 
# for numpy | array (array work every element | element wise)
start1 = time.time()
sum2 = 0
arr = np.arange(1000000)*2
sum2 = arr.sum()
end1 = time.time()
print("for array ",sum2,end1-start1)
 

for list 999999000000 0.11792540550231934
for array  -728379968 0.005287647247314453


In [5]:
arr = np.zeros(5)
print(arr)

arr1 = np.zeros((2,3))#2d array
print(arr1)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = np.full((5),7) #2d
print (arr)

[7 7 7 7 7]


In [9]:
print("2d ones start ")
arr = np.zeros(5)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

2d ones start 
[0. 0. 0. 0. 0.]
(5,)
1
5
float64


In [28]:
arr= np.arange(6)
arr1=arr.reshape(2,3)
print(arr1)

[[0 1 2]
 [3 4 5]]


In [34]:
arr=np.arange(6).reshape(2,3)
print(arr)
arr_new1=arr.ravel()
arr_new1[0]=200
print(arr)
arr.transpose()

[[0 1 2]
 [3 4 5]]
[[200   1   2]
 [  3   4   5]]


array([[200,   3],
       [  1,   4],
       [  2,   5]])